### ISSUE TITLE
Custom Properties, Defaults and Definitions [18Jan2018-1146]

### ISSUE THREAD

**Issue by jinnerbichler** [nimble-platform/catalog-service#10]
Path: 
 https://nimble-platform.salzburgresearch.at/nimble/frontend/#/catalogue/catalogue

Description of the issue:

-      Custom properties cannot be BOOLEAN type. This could be useful for many properties.

-      Base quantity value (Unit) could be inserted by default with no warning.

**Comment by dogukan10** [comment]
Resolved with commit nimble-platform/frontend-service@dd7dd85
