### ISSUE TITLE
Product filtering and sorting

### ISSUE THREAD

**Issue by jinnerbichler** [nimble-platform/catalog-service#14]
Product filtering and sorting (e.g. per type) are useful. 
**Additional details about this requirement:**

- Filtering by product type should be more visible on the filtering the resultant products after search.
- Filtering by quantity criteria should be more user friendly. Now, the units and actual value are stored in filter elements. For example, delivery_time (2) and delivery_time_unit (week) are presented as different filters.

**Comment by dogukan10** [comment]
In catalogue page, filtering (by category) and sorting (by price) products are available and after search, filtering by product type also is much more visible.
Filtering by quantity criteria will be covered by issue nimble-platform/frontend-service#54
