### ISSUE TITLE
"catalog-service" + "catalog-service-micro" use the same group and artifact ids

### ISSUE THREAD

**Issue by iot365** [nimble-platform/catalog-service#4]
- [catalog-service](https://github.com/nimble-platform/catalog-service/blob/302cc0bf6b351d09f3acf8fe4b25ed93930ea89e/catalogue-service/pom.xml#L11)
```
	<groupId>eu.nimble.core.service.catalogue</groupId>
	<artifactId>catalogue-service</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>Catalogue Service Backend Implementation</name>
```

- [catalog-service-micro](https://github.com/nimble-platform/catalog-service/blob/9cd0945be66785e5d59fa7401da22064527324aa/catalogue-service-micro/pom.xml#L8)
```
	<groupId>eu.nimble.core.service.catalogue</groupId>
	<artifactId>catalogue-service</artifactId>
	<version>0.0.1</version>
	<name>Catalogue Service Spring Boot Rest</name>
```

**Comment by dogukan10** [comment]
Resolved with commit 226385d
